# Generated by Django 6.0.4 on 2026-05-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('tables_count', models.IntegerField(default=0)),
                ('charset', models.CharField(default='utf8mb4', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('quota', models.CharField(max_length=50)),
                ('used', models.CharField(max_length=50)),
                ('used_percent', models.IntegerField(default=0)),
                ('dkim_status', models.CharField(default='Active', max_length=20)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=100)),
                ('php_version', models.CharField(default='8.3', max_length=10)),
                ('disk_used', models.CharField(max_length=50)),
                ('disk_percent', models.IntegerField(default=0)),
                ('ssl_status', models.CharField(choices=[('active', 'Active'), ('expiring', 'Expiring'), ('none', 'None')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
