# Generated by Django 6.0.4 on 2026-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disk_space', models.BigIntegerField(help_text='Disk space in MB')),
                ('bandwidth', models.BigIntegerField(help_text='Bandwidth in MB')),
                ('max_websites', models.IntegerField(default=1)),
                ('max_databases', models.IntegerField(default=1)),
                ('max_emails', models.IntegerField(default=1)),
                ('max_ftp_accounts', models.IntegerField(default=1)),
                ('max_subdomains', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
