# Generated by Django 6.0.4 on 2026-05-20 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('php_version', models.CharField(default='8.3', max_length=10)),
                ('doc_root', models.CharField(max_length=512)),
                ('is_ssl_enabled', models.BooleanField(default=False)),
                ('ssl_cert_path', models.CharField(blank=True, max_length=512, null=True)),
                ('ssl_key_path', models.CharField(blank=True, max_length=512, null=True)),
                ('disk_limit', models.BigIntegerField(default=1024)),
                ('disk_used', models.BigIntegerField(default=0)),
                ('bandwidth_limit', models.BigIntegerField(default=10240)),
                ('bandwidth_used', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='websites.website')),
            ],
        ),
    ]
